version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: lunchbuddy
      POSTGRES_USER: lunchbuddy
      POSTGRES_PASSWORD: lunchbuddy_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lunchbuddy -d lunchbuddy"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: "10m"

  bot:
    build: .
    environment:
      - DATABASE_URL=postgresql://lunchbuddy:lunchbuddy_password@db:5432/lunchbuddy
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"

volumes:
  postgres_data:
